sudo: required
dist: trusty
language: cpp
compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev  libboost-filesystem-dev libboost-test-dev libboost-thread-dev cmake 

install:
  - cd ${TRAVIS_BUILD_DIR}

before_script:
   - cmake -DCMAKE_BUILD_TYPE=Release .

script: 
   - make -j2
