build_image: shippableimages/ubuntu1404_python
language: cpp
compiler:
  - clang
  - gcc

before_install:
  #- pip install --user cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get update -qq
  - sudo apt-get update
  - sudo apt-get install libboost1.53-all-dev
  - sudo apt-get install -y cmake

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - cd ${TRAVIS_BUILD_DIR}
  - gcc --version

before_script:
   - cmake .

script: 
   - make -j2
#&& ctest .

#after_success:
#  - coveralls --exclude libmemseries --exclude tests --gcov-options '\-lp'
