sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev  libboost-filesystem-dev cmake

install:
  - cd ${TRAVIS_BUILD_DIR}
  - gcc --version

before_script:
   - cmake .

script: 
   - make -j2
