sudo: required
dist: trusty
language: cpp
compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev  libboost-filesystem-dev libboost-test-dev libboost-thread-dev cmake 
  - pip install --user cpp-coveralls

install:
  - cd ${TRAVIS_BUILD_DIR}

before_script:
   - cmake -DCMAKE_BUILD_TYPE=Coverage .

script: 
   - make -j2
   - ls
   - cd bin
   - ./utils_test
   - ls

after_success:
   - ls
   - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
